# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Deploy Angular

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.21.3'

    - name: Install Dependencies
      working-directory: html_source
      run: npm i

    - name: Build Angular App
      working-directory: html_source
      run: npm run build

    - name: Commit and Push Changes
      run: |
        git config --global user.name '${{ secrets.GITHUB_USER }}'
        git config --global user.email '${{ secrets.GITHUB_EMAIL }}'
        git add .
        git commit -m 'Auto-build Angular app'
        git push origin ${{ github.ref }}
